spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
admin.username=${ADMIN_USERNAME:Timmy45G}
admin.access.pin=${ADMIN_ACCESS_PIN:1234}
