package com.fcmobtourn.service;
import com.fasterxml.jackson.databind.JsonNode; import com.fasterxml.jackson.databind.ObjectMapper; import org.springframework.beans.factory.annotation.Value; import org.springframework.http.*; import org.springframework.stereotype.Service; import org.springframework.web.client.RestTemplate; import java.util.*;
@Service public class AIService {
 private final ObjectMapper mapper=new ObjectMapper(); private final RestTemplate http=new RestTemplate();
 @Value("${openrouter.api.key:}") private String apiKey; @Value("${openrouter.model:openrouter/free}") private String model;
 public int analyzeSquadScreenshot(String image){try{return ask(image,"Read the FC Mobile squad overall rating. Return JSON only: {\"ovr\": number}").path("ovr").asInt(125);}catch(Exception e){return 125;}}
 public Map<String,Object> analyzeMatchScreenshot(String image,String home,String away){try{JsonNode j=ask(image,"Read final score for "+home+" versus "+away+". Return JSON only: {\"homeTeam\": string,\"awayTeam\": string,\"homeScore\": number,\"awayScore\": number,\"confidence\":\"high\"|\"low\",\"teamsMatch\": boolean}. Set teamsMatch false if either displayed team is not the requested fixture team.");return Map.of("homeTeam",j.path("homeTeam").asText(""),"awayTeam",j.path("awayTeam").asText(""),"homeScore",j.path("homeScore").asInt(-1),"awayScore",j.path("awayScore").asInt(-1),"confidence",j.path("confidence").asText("low"),"teamsMatch",j.path("teamsMatch").asBoolean(false));}catch(Exception e){return Map.of("homeScore",-1,"awayScore",-1,"confidence","low","teamsMatch",false);}}
 private JsonNode ask(String image,String instruction)throws Exception{if(apiKey.isBlank())throw new IllegalStateException("OPENROUTER_API_KEY is not configured");String data=image.startsWith("data:")?image:"data:image/jpeg;base64,"+image;Map<String,Object> body=Map.of("model",model,"temperature",0.1,"max_tokens",120,"messages",List.of(Map.of("role","user","content",List.of(Map.of("type","text","text",instruction),Map.of("type","image_url","image_url",Map.of("url",data))))));HttpHeaders h=new HttpHeaders();h.setBearerAuth(apiKey);h.setContentType(MediaType.APPLICATION_JSON);String raw=http.postForEntity("https://openrouter.ai/api/v1/chat/completions",new HttpEntity<>(body,h),String.class).getBody();String content=mapper.readTree(raw).path("choices").get(0).path("message").path("content").asText().replace("```json","").replace("```","").trim();return mapper.readTree(content);}
}
